name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --release --target x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v4
      with:
        name: z407-puck
        path: target/x86_64-pc-windows-msvc/release/z407-puck.exe